# Generated by Django 5.0.1 on 2024-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('travelPlanId', models.CharField(max_length=30)),
                ('bookingId', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=8)),
                ('member', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('end_date', models.DateField()),
                ('des', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=30)),
                ('member', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneNo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
